### ISSUE TITLE
Refactoring maybe needed here ? What about using argparse ?

### ISSUE THREAD

**Issue by HarishHary** [beauthi/phylogenetic-tree#1]
https://github.com/beauthi/phylogenetic-tree/blob/a80a5a1ab14374427155eef5b0989ab1b724cbf1/src/phylo.py#L122

Argparse:
https://docs.python.org/2/library/argparse.html#module-argparse

**Comment by beauthi** [comment]
fixed in commit 056631f81d8fb69682f2e8b2ff84b86634511737
