### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by emilpaulitz** [beauthi/phylogenetic-tree#2]
This is the best documented UPGMA implementation I found, but it has no license, so I cannot legally use it (as discussed [here](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)) Please consider adding an open source license if you would like people to use it :)

**Comment by beauthi** [comment]
Hi @emilpaulitz, thanks for pointing this out! Just added an MIT license, hope that fits your needs. I'll close the issue after your confirmation :)

**Comment by emilpaulitz** [comment]
That's great, thank you for the fast response! :)
